container updated

diff --git a/.github/workflows/github-actions-ci.yml b/.github/workflows/github-actions-ci.yml
--- a/.github/workflows/github-actions-ci.yml
+++ b/.github/workflows/github-actions-ci.yml
@@ -1,16 +1,57 @@
-name: Node js app deploy to EKS
+name: Argo CD GitOps CI/CD
+
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
 
 jobs:
-  deploy:
+  build:
+    name: Build and Push the image
     runs-on: ubuntu-latest
+
     steps:
-    - name: Checkout code
+    - name: Check out code
       uses: actions/checkout@v3
+
+    - name: Bump version
+      id: bump_version
+      run: |
+        chmod +x bump_version.sh && ./bump_version.sh
+        new_version=$(cat VERSION)
+        echo "::set-output name=new_version::$new_version"
+
+    - name: Commit new version
+      run: |
+        git config --global user.name 'sosotechnologies'
+        git config --global user.email 'sosotech2000@gmail.com'
+        git add VERSION
+        git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }}" || echo "No changes to commit"
+        git stash
+        git pull --rebase origin main
+        git stash pop || echo "No stashed changes"
+        git push origin main
+
+    - name: Build the Docker image
+      run: |
+        docker build -t ${{ steps.bump_version.outputs.new_version }} .
+
+    - name: Run Trivy vulnerability scanner
+      uses: aquasecurity/trivy-action@master
+      with:
+        image-ref: '${{ steps.bump_version.outputs.new_version }}'
+        format: 'table'
+        exit-code: '0'  # Change exit code to 0 to prevent pipeline failure
+        ignore-unfixed: true
+        vuln-type: 'os,library'
+        severity: 'MEDIUM,HIGH,CRITICAL'
+        output: 'trivy-report.txt'  # Save the report to a file
+
+    - name: Upload Trivy report
+      uses: actions/upload-artifact@v3
+      with:
+        name: trivy-report
+        path: trivy-report.txt
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
@@ -23,13 +64,16 @@ jobs:
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
 
-    - name: Fetch Git Tags
-      run: git fetch --tags
-
-    - name: Bump Version
+    - name: Tag and Push Docker image to Amazon ECR
       run: |
-        chmod +x ./bump-version.sh
-        ./bump-version.sh
+        IMAGE_TAG=${{ steps.bump_version.outputs.new_version }}
+        ECR_REGISTRY=368085106192.dkr.ecr.us-east-1.amazonaws.com
+        REPOSITORY=xcite
+        docker tag $IMAGE_TAG $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
+        docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
+        docker tag $IMAGE_TAG $ECR_REGISTRY/$REPOSITORY:latest
+        docker push $ECR_REGISTRY/$REPOSITORY:latest
+
 
     - name: Build, tag, and push docker image to Amazon ECR
       env:
@@ -39,4 +83,47 @@ jobs:
       run: |
         docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
+    
+
+# name: Node js app deploy to EKS
+# on:
+#   push:
+#     branches: [ "main" ]
+#   pull_request:
+#     branches: [ "main" ]
+
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v3
+
+#     - name: Configure AWS Credentials
+#       uses: aws-actions/configure-aws-credentials@v1
+#       with:
+#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#         aws-region: us-east-1
+
+#     - name: Login to Amazon ECR
+#       id: login-ecr
+#       uses: aws-actions/amazon-ecr-login@v1
+
+#     - name: Fetch Git Tags
+#       run: git fetch --tags
+
+#     - name: Bump Version
+#       run: |
+#         chmod +x ./bump-version.sh
+#         ./bump-version.sh
+
+#     - name: Build, tag, and push docker image to Amazon ECR
+#       env:
+#         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#         REPOSITORY: xcite
+#         IMAGE_TAG: ${{ env.NEW_VERSION }}
+#       run: |
+#         docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
+#         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
     
